In [4]:
import torch

In [5]:
print (torch.__version__)

2.2.2


In [6]:
print(torch.cuda.is_available())

False


In [15]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([[2, 3, 4], [5, 6, 8]])
x1 = torch.zeros(6)

In [16]:
print(x.shape, y.shape)

torch.Size([3]) torch.Size([2, 3])


In [17]:
x1

tensor([0., 0., 0., 0., 0., 0.])

In [18]:
print(x.dtype)

torch.float32


In [19]:
print(y.dtype)

torch.int64


In [20]:
y2 = y.to(torch.float32)

In [21]:
y2

tensor([[2., 3., 4.],
        [5., 6., 8.]])

In [22]:
z = torch.randn(5,6)

In [23]:
z

tensor([[-0.1649,  0.0924, -0.9347,  1.3604,  0.7985,  0.0594],
        [-0.8975, -0.3058, -0.6028,  0.7094,  0.1020, -1.2794],
        [-0.8743,  0.2961, -0.6530, -0.7743, -0.7427, -1.8622],
        [ 0.8062,  1.4483,  0.6871,  0.5670,  0.4158, -0.7819],
        [ 1.8690, -1.1363, -0.3511, -0.5283, -0.6145, -0.5245]])

In [24]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [25]:
device

device(type='cpu')

In [26]:
z.to(device)

tensor([[-0.1649,  0.0924, -0.9347,  1.3604,  0.7985,  0.0594],
        [-0.8975, -0.3058, -0.6028,  0.7094,  0.1020, -1.2794],
        [-0.8743,  0.2961, -0.6530, -0.7743, -0.7427, -1.8622],
        [ 0.8062,  1.4483,  0.6871,  0.5670,  0.4158, -0.7819],
        [ 1.8690, -1.1363, -0.3511, -0.5283, -0.6145, -0.5245]])

In [45]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]]).to(device)
B = torch.tensor([[5, 1, 6], [9, 2, 1], [4, 7, 9]]).to(device)

In [43]:
C = A + B


In [44]:
C

tensor([[ 6,  3,  9],
        [13,  7,  7]])

In [46]:
C = A @ B

In [47]:
C

tensor([[35, 26, 35],
        [89, 56, 83]])

In [66]:
x = torch.tensor(3.0)
w = torch.tensor(4.0, requires_grad=True)
b = torch.tensor(6.0, requires_grad=True)

y = w * x + b
loss = (y - 10) ** 2

In [53]:
loss

tensor(64., grad_fn=<PowBackward0>)

In [54]:
loss.backward()

In [56]:
print(w.grad.item())

48.0


In [57]:
print(b.grad.item())

16.0


In [67]:
dw, db = torch.autograd.grad(loss, [w, b])

In [63]:
dw

(tensor(48.),)